
# Font Setup
font_family  Cascadia Code NF
bold_font    auto
italic_font  auto
font_size    13
modify_font cell_height 2px


# Background
background_opacity 0.99

# window
hide_window_decorations titlebar-and-corners


# GruvBox Theme
include gruvbox_dark_hard.conf

# remapping
map alt+h send_text all \x1bh
map alt+l send_text all \x1bl
map alt+] send_text all \x1b]
map alt+[ send_text all \x1b[


